---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus3-pv-claim
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
