---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus3
  labels:
    app: nexus3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus3
  template:
    metadata:
      labels:
        app: nexus3
    spec:
      serviceAccountName: nexus-registry
      volumes:
      - name: registry-vol
        persistentVolumeClaim:
          claimName: nexus3-pv-claim
      containers:
      - image: sonatype/nexus3:latest
        name: nexus
        ports:
          - containerPort: 8081
        volumeMounts:
        - name: registry-vol
          mountPath: /nexus-data
          subPath: data
---
apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  selector:
    app: nexus3
  #type: ClusterIP
  type: NodePort  # Adicione o tipo de serviço se necessário
  ports:
  - name: http
    port: 8081
    protocol: TCP
    targetPort: 8081
    nodePort: 31229
