---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus3
  labels:
    app: nexus3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus3
  template:
    metadata:
      labels:
        app: nexus3
    spec:
      serviceAccountName: nexus-registry
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
          - key: nginx.conf
            path: nginx.conf
      - name: registry-vol
        persistentVolumeClaim:
          claimName: nexus3-pv-claim
      containers:
      - image: nginx:latest
        name: nginx
        resources:
          limits:
            memory: "32Mi"
            cpu: "50m"
        ports:
        - containerPort: 80
          name: http-nginx
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
      - image: sonatype/nexus3:latest
        name: nexus
        ports:
          - containerPort: 8081
            name: http       # nexus3-admin
          - containerPort: 8082
            name: http-dk-1  # docker-public
          - containerPort: 8083
            name: http-dk-2  # docker-private
          - containerPort: 8084
            name: http-dk-3  # docker-jenkins-builds-public
          - containerPort: 8085
            name: http-dk-4  # docker-jenkins-builds-private
          - containerPort: 8086
            name: http-dk-5  # docker-hub
          - containerPort: 8444
            name: https-dk-1 # docker-public
          - containerPort: 8445
            name: https-dk-2 # docker-private
          - containerPort: 8446
            name: https-dk-3 # docker-jenkins-builds-public
          - containerPort: 8447
            name: https-dk-4 # docker-jenkins-builds-private
          - containerPort: 8448
            name: https-dk-5 # docker-hub
        volumeMounts:
        - name: registry-vol
          mountPath: /nexus-data
          subPath: data
---
apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  selector:
    app: nexus3
  #type: ClusterIP
  type: NodePort  # Adicione o tipo de serviço se necessário
  ports:
  - name: http-nginx
    port: 80
    protocol: TCP
    targetPort: 80
  - name: http
    port: 8081
    protocol: TCP
    targetPort: 8081
    nodePort: 31229
  - port: 8082
    name: http-dk-1  # docker-public
    protocol: TCP
    targetPort: 8082
  - port: 8083
    name: http-dk-2  # docker-private
    protocol: TCP
    targetPort: 8083
  - port: 8084
    name: http-dk-3  # docker-jenkins-builds-public
    protocol: TCP
    targetPort: 8084
  - port: 8085
    name: http-dk-4  # docker-jenkins-builds-private
    protocol: TCP
    targetPort: 8085
  - port: 8086
    name: http-dk-5  # docker-hub
    protocol: TCP
    targetPort: 8086
  - port: 8444
    name: https-dk-1 # docker-public
    protocol: TCP
    targetPort: 8444
  - port: 8445
    name: https-dk-2 # docker-private
    protocol: TCP
    targetPort: 8445
  - port: 8446
    name: https-dk-3 # docker-jenkins-builds-public
    protocol: TCP
    targetPort: 8446
  - port: 8447
    name: https-dk-4 # docker-jenkins-builds-private
    protocol: TCP
    targetPort: 8447
  - port: 8448
    name: https-dk-5 # docker-hub
    protocol: TCP
    targetPort: 8448
